version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: cryptomoney-postgres
    environment:
      POSTGRES_DB: cryptomoney
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - cryptomoney-network
    restart: unless-stopped

  # Redis for caching and sessions
  redis:
    image: redis:7-alpine
    container_name: cryptomoney-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - cryptomoney-network
    restart: unless-stopped

  # Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cryptomoney-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/cryptomoney
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - cryptomoney-network
    restart: unless-stopped
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

  # Nginx reverse proxy (optional)
  nginx:
    image: nginx:alpine
    container_name: cryptomoney-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - app
    networks:
      - cryptomoney-network
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:

networks:
  cryptomoney-network:
    driver: bridge
